In [31]:
import torch
def expand(st_dict, new_path):
    st_dict['layoutlmv3.embeddings.position_ids'] = torch.cat(
        (st_dict['layoutlmv3.embeddings.position_ids'], st_dict['layoutlmv3.embeddings.position_ids'])
        , dim=1)
    st_dict['layoutlmv3.embeddings.position_embeddings.weight'] = torch.cat(
        (st_dict['layoutlmv3.embeddings.position_embeddings.weight'], st_dict['layoutlmv3.embeddings.position_embeddings.weight'])
        , dim=0)
    print("expand position_ids to ", st_dict['layoutlmv3.embeddings.position_ids'].shape)
    print("expand position_embeddings.weight to ", st_dict['layoutlmv3.embeddings.position_embeddings.weight'].shape)
    torch.save(st_dict, new_path)
    return st_dict

def expand_truncate(st_dict, new_path):
    st_dict['layoutlmv3.embeddings.position_ids'] = torch.cat(
        (st_dict['layoutlmv3.embeddings.position_ids'], st_dict['layoutlmv3.embeddings.position_ids'])
        , dim=1)
    st_dict['layoutlmv3.embeddings.position_embeddings.weight'] = torch.cat(
        (st_dict['layoutlmv3.embeddings.position_embeddings.weight'], st_dict['layoutlmv3.embeddings.position_embeddings.weight'])
        , dim=0)
    print("expand position_ids to ", st_dict['layoutlmv3.embeddings.position_ids'].shape)
    print("expand position_embeddings.weight to ", st_dict['layoutlmv3.embeddings.position_embeddings.weight'].shape)
    for k in list(st_dict.keys()):
        if k.startswith('classifier.'):
            st_dict.pop(k)
            print("pop ", k)
    torch.save(st_dict, new_path)
    return st_dict

In [24]:
from layoutlmft.models.layoutlmv3.modeling_layoutlmv3 import LayoutLMv3ForRelationExtraction, LayoutLMv3ForTokenClassification
model = LayoutLMv3ForTokenClassification.from_pretrained(
    "HYPJUDY/layoutlmv3-large-finetuned-funsd"
)

Some weights of LayoutLMv3ForTokenClassification were not initialized from the model checkpoint at HYPJUDY/layoutlmv3-large-finetuned-funsd and are newly initialized: ['layoutlmv3.encoder.layer.12.attention.self.lam', 'layoutlmv3.encoder.layer.6.attention.self.lam', 'layoutlmv3.encoder.layer.7.attention.self.lam', 'layoutlmv3.encoder.layer.22.attention.self.lam', 'layoutlmv3.encoder.layer.18.attention.self.lam', 'layoutlmv3.encoder.layer.2.attention.self.lam', 'layoutlmv3.encoder.layer.23.attention.self.lam', 'layoutlmv3.encoder.layer.9.attention.self.lam', 'layoutlmv3.encoder.layer.14.attention.self.lam', 'layoutlmv3.encoder.layer.10.attention.self.lam', 'layoutlmv3.encoder.layer.4.attention.self.lam', 'layoutlmv3.encoder.layer.1.attention.self.lam', 'layoutlmv3.encoder.layer.0.attention.self.lam', 'layoutlmv3.encoder.layer.11.attention.self.lam', 'layoutlmv3.encoder.layer.5.attention.self.lam', 'layoutlmv3.encoder.layer.8.attention.self.lam', 'layoutlmv3.encoder.layer.15.attention.se

In [35]:
st_dict = model.state_dict()

In [33]:
expand(st_dict, "layoutlmv3-large-ner-1028/pytorch_model.bin")

expand position_ids to  torch.Size([1, 1028])
expand position_embeddings.weight to  torch.Size([1028, 1024])


OrderedDict([('layoutlmv3.cls_token',
              tensor([[[ 0.0048,  0.0050, -0.0061,  ...,  0.0044,  0.0049, -0.0035]]])),
             ('layoutlmv3.pos_embed',
              tensor([[[ 0.0048,  0.0050, -0.0061,  ...,  0.0044,  0.0049, -0.0035],
                       [-0.0227, -0.1193, -0.0386,  ...,  0.0439,  0.0279,  0.0317],
                       [-0.0020, -0.0177, -0.0014,  ...,  0.0200,  0.0133, -0.0172],
                       ...,
                       [-0.0249,  0.0348, -0.0216,  ...,  0.0209,  0.0107,  0.0307],
                       [-0.0321,  0.0187, -0.0043,  ...,  0.0219, -0.0361,  0.0521],
                       [-0.0395, -0.0270,  0.0373,  ..., -0.0060, -0.0990,  0.0855]]])),
             ('layoutlmv3.embeddings.position_ids',
              tensor([[  0,   1,   2,  ..., 511, 512, 513]])),
             ('layoutlmv3.embeddings.word_embeddings.weight',
              tensor([[-0.1047,  0.0190,  0.0801,  ...,  0.0457,  0.0123, -0.0313],
                      [ 0.0069, 

In [36]:
expand_truncate(st_dict, "layoutlmv3-large-re-1028/pytorch_model.bin")

expand position_ids to  torch.Size([1, 1028])
expand position_embeddings.weight to  torch.Size([1028, 1024])
pop  classifier.weight
pop  classifier.bias


OrderedDict([('layoutlmv3.cls_token',
              tensor([[[ 0.0048,  0.0050, -0.0061,  ...,  0.0044,  0.0049, -0.0035]]])),
             ('layoutlmv3.pos_embed',
              tensor([[[ 0.0048,  0.0050, -0.0061,  ...,  0.0044,  0.0049, -0.0035],
                       [-0.0227, -0.1193, -0.0386,  ...,  0.0439,  0.0279,  0.0317],
                       [-0.0020, -0.0177, -0.0014,  ...,  0.0200,  0.0133, -0.0172],
                       ...,
                       [-0.0249,  0.0348, -0.0216,  ...,  0.0209,  0.0107,  0.0307],
                       [-0.0321,  0.0187, -0.0043,  ...,  0.0219, -0.0361,  0.0521],
                       [-0.0395, -0.0270,  0.0373,  ..., -0.0060, -0.0990,  0.0855]]])),
             ('layoutlmv3.embeddings.position_ids',
              tensor([[  0,   1,   2,  ..., 511, 512, 513]])),
             ('layoutlmv3.embeddings.word_embeddings.weight',
              tensor([[-0.1047,  0.0190,  0.0801,  ...,  0.0457,  0.0123, -0.0313],
                      [ 0.0069, 

In [21]:
for k,v in model.named_parameters():
    print(k, v.size())

layoutlmv3.cls_token torch.Size([1, 1, 1024])
layoutlmv3.pos_embed torch.Size([1, 197, 1024])
layoutlmv3.embeddings.word_embeddings.weight torch.Size([50265, 1024])
layoutlmv3.embeddings.token_type_embeddings.weight torch.Size([1, 1024])
layoutlmv3.embeddings.LayerNorm.weight torch.Size([1024])
layoutlmv3.embeddings.LayerNorm.bias torch.Size([1024])
layoutlmv3.embeddings.position_embeddings.weight torch.Size([514, 1024])
layoutlmv3.embeddings.x_position_embeddings.weight torch.Size([1024, 171])
layoutlmv3.embeddings.y_position_embeddings.weight torch.Size([1024, 171])
layoutlmv3.embeddings.h_position_embeddings.weight torch.Size([1024, 170])
layoutlmv3.embeddings.w_position_embeddings.weight torch.Size([1024, 170])
layoutlmv3.encoder.layer.0.attention.self.lam torch.Size([])
layoutlmv3.encoder.layer.0.attention.self.query.weight torch.Size([1024, 1024])
layoutlmv3.encoder.layer.0.attention.self.query.bias torch.Size([1024])
layoutlmv3.encoder.layer.0.attention.self.key.weight torch.Siz